pipeline:
  identifier: Build_ipreetgs_microService_TXApplication_1702456960000
  name: Build microService_TXApplication
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702454246010
        repoName: ipreetgs/microService_TXApplication
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
